# Generated by Django 3.2 on 2022-05-20 19:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Manga',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('type', models.CharField(choices=[('Manhua', 'manhwa'), ('Manhua', 'manhua'), ('Manga', 'manga'), ('Comics', 'comics'), ('Novel', 'novel')], default='Manga', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('publication_date', models.DateField()),
                ('publication_type', models.CharField(choices=[('Monthly', 'monthly'), ('Weekly', 'weekly'), ('Daily', 'daily')], default='seasonal', max_length=10)),
                ('number_of_chapters', models.IntegerField(default=0)),
                ('number_of_members', models.IntegerField(default=0)),
                ('rate', models.FloatField(default=3)),
            ],
        ),
        migrations.CreateModel(
            name='ModelGenre',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('object_id', models.PositiveIntegerField(null=True)),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
                ('tag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='model_tag', to='manga.genre')),
            ],
        ),
    ]
