# Generated by Django 4.0.5 on 2022-06-16 00:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manga', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='manga',
            name='publication_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
