# Generated by Django 3.2 on 2021-12-14 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anime', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='manga',
            name='number_of_chapters',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='manga',
            name='pub_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='manga',
            name='rate',
            field=models.FloatField(default=3),
        ),
    ]
