# Generated by Django 3.2.9 on 2021-12-14 18:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('anime', '0003_manga_number_of_members'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='manga',
            name='pub_date',
        ),
    ]
