# Generated by Django 3.2 on 2021-12-14 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anime', '0004_remove_manga_pub_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chapter',
            name='season',
            field=models.IntegerField(default=1),
        ),
    ]
