# Generated by Django 3.2.9 on 2021-12-15 22:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anime', '0005_alter_chapter_season'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='manga',
            name='kind',
        ),
        migrations.AddField(
            model_name='manga',
            name='genres',
            field=models.CharField(default='Advanture', max_length=10),
        ),
    ]
