# Generated by Django 3.2 on 2021-12-17 20:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('anime', '0006_auto_20211216_0007'),
    ]

    operations = [
        migrations.RenameField(
            model_name='chapter',
            old_name='Chapter_number',
            new_name='chapter_number',
        ),
    ]
