# Generated by Django 3.2.9 on 2021-12-21 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anime', '0008_reply'),
    ]

    operations = [
        migrations.AddField(
            model_name='chapter',
            name='imgs',
            field=models.TextField(null=True),
        ),
    ]
