# Generated by Django 3.2 on 2022-05-20 19:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0011_auto_20220520_1957'),
        ('manga', '0001_initial'),
        ('anime', '0010_comment_pub_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chapter',
            name='manga',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='manga.manga'),
        ),
        migrations.AlterField(
            model_name='review',
            name='manga',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='manga.manga'),
        ),
        migrations.DeleteModel(
            name='Manga',
        ),
    ]
