# Generated by Django 3.2 on 2022-05-20 21:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('anime', '0011_auto_20220520_1957'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='chapter',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='user',
        ),
        migrations.RemoveField(
            model_name='reply',
            name='comment',
        ),
        migrations.RemoveField(
            model_name='reply',
            name='user',
        ),
        migrations.RemoveField(
            model_name='review',
            name='manga',
        ),
        migrations.RemoveField(
            model_name='review',
            name='user',
        ),
        migrations.DeleteModel(
            name='Chapter',
        ),
        migrations.DeleteModel(
            name='Comment',
        ),
        migrations.DeleteModel(
            name='reply',
        ),
        migrations.DeleteModel(
            name='Review',
        ),
    ]
