# Generated by Django 4.0.5 on 2022-06-16 15:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lists', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listitem',
            name='lista',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='listitem_set', to='lists.list'),
        ),
    ]
