# Generated by Django 3.2.9 on 2021-12-13 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_remove_profile_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='location',
            field=models.CharField(default='Egypt', max_length=20),
        ),
        migrations.AlterField(
            model_name='profile',
            name='pic',
            field=models.ImageField(default='default.png', upload_to='profile_images'),
        ),
    ]
