# Generated by Django 3.2 on 2021-12-17 21:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('anime', '0007_rename_chapter_number_chapter_chapter_number'),
        ('user', '0004_favorit'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='favorit',
            name='chapter',
        ),
        migrations.AddField(
            model_name='favorit',
            name='manga',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='anime.manga'),
        ),
    ]
