# Generated by Django 3.2.9 on 2021-12-24 14:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0008_notification'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notification',
            name='user',
        ),
    ]
