# Generated by Django 3.2 on 2022-05-20 19:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('manga', '0001_initial'),
        ('user', '0010_auto_20211224_1627'),
    ]

    operations = [
        migrations.AlterField(
            model_name='favorit',
            name='manga',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='manga.manga'),
        ),
        migrations.AlterField(
            model_name='listitem',
            name='manga',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='manga.manga'),
        ),
    ]
